defmodule GlamCam.Repo.Migrations.AddBlueskyLinkToPost do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:posts), :bluesky_handle, to: :tag_bluesky_handle

    alter table(:posts) do
      add :bluesky_link, :text
    end
  end

  def down do
    alter table(:posts) do
      remove :bluesky_link
    end

    rename table(:posts), :tag_bluesky_handle, to: :bluesky_handle
  end
end