defmodule GlamCam.Repo.Migrations.RemoveTagAddHandleToPost do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      add :bluesky_handle, :text
    end
  end

  def down do
    alter table(:posts) do
      remove :bluesky_handle
    end
  end
end