defmodule GlamCam.Repo.Migrations.AddTokenToPosts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      add :token, :text, null: false
    end
  end

  def down do
    alter table(:posts) do
      remove :token
    end
  end
end