defmodule GlamCam.Repo.Migrations.AddPosts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:posts, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :status, :text, null: false
      add :token, :text, null: false
      add :image, :binary, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:posts)
  end
end